"""
Command Line Interface (CLI) for ALIS.

Purpose:
--------
This module provides a simple terminal-based interface for
interacting with the ALIS chatbot.
"""


def get_user_query():
    """
    Read a question from the user.

    Returns
    -------
    str
        User's input question.
    """

    return input("\nAsk ALIS: ")


def display_response(response):
    """
    Display the chatbot's response.

    Parameters
    ----------
    response : str
        Formatted response generated by the Response Handler.
    """

    print("\n----------------------------------------")
    print(response)
    print("----------------------------------------")